name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Build the Makefile using qmake
        run: qmake

      - name: Build the project using make
        run: make
